name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Everything
      run: go build -v ./...

    - name: Build CInterop
      run: go build -buildmode=c-shared -o publish/issuer.dll issuer/cinterface/cinterface.go

    - name: Publish archive with CInterop artifacts
      uses: actions/upload-artifact@v2
      with:
        name: publish-folder
        path: |
          publish

    - name: Test
      run: go test -v ./...
